export type GifOverride = { url?: string; query?: string; link?: string; title?: string };
export type GifOverridesMap = Record<string, GifOverride[]>;

// Customize cartoon/professional GIFs per keyword
// Only used when the specific keyword is present in the user text/answer
export const gifOverrides: GifOverridesMap = {
  // 🏢 General Office
  office: [{ url: "https://media.tenor.com/gxWRzeiHg4MAAAAj/pengu-pudgy.gif" }],
  offices: [{ url: "https://media.tenor.com/gxWRzeiHg4MAAAAj/pengu-pudgy.gif" }],
  headquarters: [{ url: "https://media.tenor.com/WR44thrgZBkAAAAj/pengu-pudgy.gif" }],
  branch: [{ url: "https://media.tenor.com/WR44thrgZBkAAAAj/pengu-pudgy.gif" }],
  workspace: [{ url: "https://media.tenor.com/WR44thrgZBkAAAAj/pengu-pudgy.gif" }],
  work: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],
  team: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  employee: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  staff: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  colleagues: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  members: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  group: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  squad: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  crew: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  department: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  division: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  coworkers: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  teammates: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  personnel: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  workforce: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  company: [{ url: "https://media.tenor.com/WR44thrgZBkAAAAj/pengu-pudgy.gif" }],
  corporation: [{ url: "https://media.tenor.com/WR44thrgZBkAAAAj/pengu-pudgy.gif" }],
  firm: [{ url: "https://media.tenor.com/WR44thrgZBkAAAAj/pengu-pudgy.gif" }],
  enterprise: [{ url: "https://media.tenor.com/WR44thrgZBkAAAAj/pengu-pudgy.gif" }],
  workplace: [{ url: "https://media.tenor.com/WR44thrgZBkAAAAj/pengu-pudgy.gif" }],
  desk: [{ url: "https://media.tenor.com/WR44thrgZBkAAAAj/pengu-pudgy.gif" }],
  cubicle: [{ url: "https://media.tenor.com/WR44thrgZBkAAAAj/pengu-pudgy.gif" }],
  job: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],
  task: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],
  assignment: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],
  duty: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],
  labor: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],
  profession: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],
  career: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],

  // 📊 Meetings & Collaboration
  meeting: [{ url: "https://media.tenor.com/hmxgz6bYMVQAAAAi/team-business.gif" }],
  conference: [{ url: "https://media.tenor.com/hmxgz6bYMVQAAAAi/team-business.gif" }],
  boardroom: [{ url: "https://media.tenor.com/hmxgz6bYMVQAAAAi/team-business.gif" }],
  presentation: [{ url: "https://media.tenor.com/hmxgz6bYMVQAAAAi/team-business.gif" }],
  brainstorming: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  discussion: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  collaboration: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  call: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  huddle: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  gathering: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  assembly: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  summit: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  session: [{ url: "https://media.tenor.com/hmxgz6bYMVQAAAAi/team-business.gif" }],
  webinar: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  video: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  sync: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  standup: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  review: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  planning: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  coordination: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],

  // 💻 IT & Software
  software: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  development: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  coding: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExbnQ1Y2xnZ3FlZ253MjE2MWU3YXRka3EwbXEyazdidWRtbTl3YXg0ciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/L1R1tvI9svkIWwpVYr/giphy.gif" }],
  programming: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  technology: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  innovation: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  digital: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  IT: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  project: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  solution: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  developer: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  engineer: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  coder: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExbnQ1Y2xnZ3FlZ253MjE2MWU3YXRka3EwbXEyazdidWRtbTl3YXg0ciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/L1R1tvI9svkIWwpVYr/giphy.gif" }],
  programmer: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  hacker: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExbnQ1Y2xnZ3FlZ253MjE2MWU3YXRka3EwbXEyazdidWRtbTl3YXg0ciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/L1R1tvI9svkIWwpVYr/giphy.gif" }],
  tech: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  app: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  application: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  platform: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  system: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],

  // 🎯 Services
  service: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  services: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  consulting: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  support: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  help: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  assistance: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  aid: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  customer: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  client: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  advisor: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  guidance: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],

  // 📍 Locations
  location: [{ url: "https://media.tenor.com/DbNnATR72C0AAAAm/moon-eclipse.gif" }],
  address: [{ url: "https://media.tenor.com/DbNnATR72C0AAAAm/moon-eclipse.gif" }],
  building: [{ url: "https://media.tenor.com/DbNnATR72C0AAAAm/moon-eclipse.gif" }],
  tower: [{ url: "https://media.tenor.com/DbNnATR72C0AAAAm/moon-eclipse.gif" }],
  site: [{ url: "https://media.tenor.com/DbNnATR72C0AAAAm/moon-eclipse.gif" }],
  venue: [{ url: "https://media.tenor.com/DbNnATR72C0AAAAm/moon-eclipse.gif" }],
  premises: [{ url: "https://media.tenor.com/DbNnATR72C0AAAAm/moon-eclipse.gif" }],
  HQ: [{ url: "https://media.tenor.com/WR44thrgZBkAAAAj/pengu-pudgy.gif" }],
  head: [{ url: "https://media.tenor.com/WR44thrgZBkAAAAj/pengu-pudgy.gif" }],

  // 👨‍💼 Roles
  ceo: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  manager: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  director: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  executive: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  founder: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  entrepreneur: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  president: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  chairman: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  supervisor: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  lead: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],

  // 🖥️ Office Items
  laptop: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  computer: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  desktop: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  monitor: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  keyboard: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  mouse: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],
  phone: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  tablet: [{ url: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd4dm9nZDlzMG55eXhhODF0Zjg1dmVnM2RvcDYzc2t3dmV1NG1jeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif" }],

  // 🚀 Growth & Business
  growth: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],
  future: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],
  transformation: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],
  business: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],
  startup: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],
  expansion: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],
  progress: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],
  advancement: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],
  success: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],
  achievement: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],
  commerce: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],
  trade: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],
  industry: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],
  venture: [{ url: "https://media.tenor.com/5MdfFZTBI5cAAAAM/cardio-workout.gif" }],

  // ☁️ Cloud & Security & Data
  cloud: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  cybersecurity: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  database: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  server: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  hosting: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  infrastructure: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  datacenter: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  security: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  protection: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  defense: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  data: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  storage: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  repository: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],

  // 🤖 AI & Automation & DevOps
  ai: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  machinelearning: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  automation: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  devops: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  debugging: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  analytics: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  chatbot: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  bot: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  intelligent: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  smart: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  automate: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  pipeline: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  deployment: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  integration: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  monitoring: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  testing: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  reporting: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],
  metrics: [{ url: "https://media.tenor.com/OKIUo_4GhLUAAAAM/thinking-think.gif" }],

  // 🏢 Culture & Functions
  culture: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  functions: [{ url: "https://media.tenor.com/9QWNsGBYSQIAAAAM/great-nice.gif" }],
  worklife: [{ url: "https://media.tenor.com/WR44thrgZBkAAAAj/pengu-pudgy.gif" }],
  balance: [{ url: "https://media.tenor.com/WR44thrgZBkAAAAj/pengu-pudgy.gif" }]
};

const overrides: GifOverridesMap = gifOverrides;
export default overrides;
